# Generated by Django 6.0.3 on 2026-05-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_gameconfirmations_gameparticipants_games_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gameconfirmations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='gameparticipants',
            options={},
        ),
        migrations.AlterModelOptions(
            name='games',
            options={},
        ),
        migrations.AlterModelOptions(
            name='organizerrequests',
            options={},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={},
        ),
        migrations.AlterModelOptions(
            name='rentals',
            options={},
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
