# Generated by Django 6.0.3 on 2026-05-12 12:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_gameconfirmations_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameconfirmations',
            name='game',
            field=models.ForeignKey(db_column='game_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.games'),
        ),
        migrations.AddField(
            model_name='gameconfirmations',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='gameparticipants',
            name='game',
            field=models.ForeignKey(db_column='game_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='main.games'),
        ),
        migrations.AddField(
            model_name='gameparticipants',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='games',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizerrequests',
            name='user',
            field=models.ForeignKey(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='game_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='games',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organizerrequests',
            name='message',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user',
            field=models.OneToOneField(db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rentals',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
